# Select what we should cache between builds
cache:
  paths:
    - vendor/
variables:
  XDEBUG_MODE: coverage

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git libzip unzip zip zlib1g-dev libxml2-dev libpcre3-dev
  # Install PHP extensions
  - docker-php-ext-install zip
  # Install & enable Xdebug for code coverage reports
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  # Install and run Composer
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

# Run our tests
# If Xdebug was installed you can generate a coverage report and see code coverage metrics.
test:7.4:
  only:
    - master
  tags:
    - default
  image: php:7.4
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
test:8.0:
  only:
    - master
  tags:
    - default
  image: php:8.0
  script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --colors=never
