# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  tags: 
    - default
  stage: deploy
  script:
    - ls
    - ls -lh
  artifacts:
    paths:
      - public
  only:
    - pages
